//
// Created by John J. Hritz on 3/29/2019.
//

#ifndef PRINCIPLES_AND_PRACTICES_SIMPLECALCULATOR_H
#define PRINCIPLES_AND_PRACTICES_SIMPLECALCULATOR_H

#include "calcparser.h"

void calculate();

#endif //PRINCIPLES_AND_PRACTICES_SIMPLECALCULATOR_H
